---
apiVersion: v1
kind: ConfigMap
metadata:
  name: chaostoolkit-resources-templates
data:
  chaostoolkit-pod.yaml: |-
    apiVersion: v1
    kind: Pod
    metadata:
      name: chaostoolkit
      labels:
        app: chaostoolkit
        app.kubernetes.io/name: chaostoolkit
    spec:
      restartPolicy: Never
      serviceAccountName: chaostoolkit
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            app.kubernetes.io/name: chaostoolkit
      containers:
      - name: chaostoolkit
        image: chaostoolkit/chaostoolkit
        imagePullPolicy: Always
        command:
        - chaos
        args:
        - run
        - $(EXPERIMENT_PATH)
        env:
        - name: CHAOSTOOLKIT_IN_POD
          value: "true"
        - name: EXPERIMENT_PATH
          value: "/home/svc/experiment.json"
        envFrom:
        - configMapRef:
            name: chaostoolkit-env
        resources:
          limits:
            cpu: 500m
            memory: 500Mi
          requests:
            cpu: 500m
            memory: 500Mi
        volumeMounts:
        - name: chaostoolkit-settings
          mountPath: /home/svc/.chaostoolkit/
          readOnly: true
        - name: chaostoolkit-experiment
          mountPath: /home/svc/experiment.json
          subPath: experiment.json
          readOnly: true
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          runAsNonRoot: true
      volumes:
      - name: chaostoolkit-settings
        secret:
          secretName: chaostoolkit-settings
      - name: chaostoolkit-experiment
        configMap:
          name: chaostoolkit-experiment

