---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
#namespace: chaostoolkit-crd

labels:
  - pairs:
      role: chaosengineering
      provider: chaostoolkit
      app: chaostoolkit-crd
      app.kubernetes.io/name: chaostoolkit
    includeSelectors: true
    includeTemplates: true

resources:
- kubernetes-crd/manifests/overlays/generic-rbac/ns.yaml
- kubernetes-crd/manifests/base
- kubernetes-crd/manifests/base/rbac
patches:  
- path: configmap.yaml
  target:
    kind: ConfigMap

